apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: t210-ingress
  namespace: t210
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  tls:
    - secretName: t210-ecsimsw-com
      hosts:
        - t210.ecsimsw.com
  rules:
    - host: t210.ecsimsw.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-server-svc
                port:
                  number: 8080

# curl -i mymarket.ecsimsw.com:32080 --resolve mymarket.ecsimsw.com:32080:192.168.0.100
# curl -i mymarket.ecsimsw.com:80 --resolve mymarket.ecsimsw.com:80:192.168.0.121
